#encoding: utf-8
defaults: &defaults
  blog:
    domain: http://0.0.0.0:80
    aritcle_page_size: 10
    comments_page_size: 10
  mailer:
    address: smtp.163.com
    port: 25
    user_name: 13188895358@163.com
    password: jr981008

development:
  <<: *defaults

production:
  <<: *defaults
